### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by lrettig** [stacksgov/updates#1]
Things to include:

- Intro the project
- Intro to weekly updates
- Intro community call
- Establishment of YouTube channel, this GitHub org and its repos
- Governance category on Blockstack community forum, and conversation there
- Community survey: draft complete, contributing
- CTA/get involved: Join the forum, join the Discord, contribute to these updates

What's missing? I posted an outline to #2, feel free to propose additions/corrections.

**Comment by joberding** [comment]
Updates should include learnings to date and next steps.

**Comment by dantrevino** [comment]
To @joberding's point above, Issue 1 should include discussion from the 2nd call as well.  Especially:
* establishment of foundation in Singapore
* criteria for Foundation board
* selection process for board

**Comment by lrettig** [comment]
Agree! I posted some basic notes from the first call [here](https://github.com/stacksgov/pm/issues/3#issuecomment-593482885). We can include and/or link these. The draft update is [here](https://github.com/stacksgov/updates/blob/update-001/updates/20200224-update-001.md), feel free to fork [the branch](https://github.com/stacksgov/updates/tree/update-001) and submit a change as a PR, or you can propose changes and I'll make them. Thanks!

**Comment by lrettig** [comment]
I factored in these suggestions, take a look: https://github.com/stacksgov/updates/blob/1379f205b76aaac816bae2c92922902bc39284dc/updates/20200224-update-001.md.

I think this is good to go. Any final thoughts or suggestions before we hit publish?

Thanks!
